### ISSUE TITLE
Question_cancer_gene_sites

### ISSUE THREAD

**Issue by FL512** [reimandlab/ActiveDriverWGSR#16]
Hi,
First of all, thank you so much for sharing such an amazing analyzing tool for us.
I believe ActiveDriverWGS can help and move my project forward.

I think I can prepare equivalent files of "cll_mutations" and "cancer_genes" by myself.
However, I have no idea how I can generate the "cancer_gene_sites" file. and I do not understand why we need it.
Will you please explain clearly what the cancer_gene_sites is and let me know how I can make this file for my analysis?
I am interested in analyzing non-coding regions such as UTR, intron, promoter and enhancer regions.

Thank you.

**Comment by reimand0** [comment]
Hello: cancer_gene_sites is an optional parameter and is not strictly
necessary for the driver analysis. It might be useful if the user is
interested in particular small sequence sites within elements. For example,
a promoter sequence of 1000 bps may contain several smaller TF binding
sites (10-20bps in size). if the optional dataset is provided, then
additional stats will be computed to ask if the small sites within the
elements are especially highly mutated. I hope this helps!

**Comment by FL512** [comment]
It helps a lot! Thank you so much.
