### ISSUE TITLE
ActiveDriver not compatible with mutation data that only contains insertions

### ISSUE THREAD

**Issue by CathyCha** [reimandlab/ActiveDriverWGSR#2]
```{r}
install.packages("ActiveDriverWGS") 
library(ActiveDriverWGS)

#example elements 
testEle <- data.frame("chr" = c("chr1", "chr1"), "start" = c(3195984, 3204562), 
                      "end" = c(3205713, 3661579	), "id" = c("uc007aet.1", "uc007aeu.1"), stringsAsFactors = FALSE)

#example insertion only mutation data
testMutIn <- data.frame("chr" = c("chr18", "chr8"), "pos1" = c(70287915, 32273077), 
                      "pos2" = c(70287915, 32273077), "ref" = c("T", "T"), 
                      "alt" = c("GA", "GA"), "patient" = c("10167", "10167"), stringsAsFactors = FALSE)

results = ActiveDriverWGS(mutations = testMutIn,
                          elements = testEle)
```

When activeDriverWGSR is run with mutation data that only consists of insertions it returns the following error 

```{r}
Error in ActiveDriverWGS(mutations = testMutIn, elements = testEle) : 
   Reference and alternate alleles must be A, T, C or G
```

This error message comes from line 128 which checks if the reference and alternative columns are "legal_DNA". 

The test examples used are indeed legal_DNA as they are sequences that consist of "G" and "A" however, the current check only allows single nucleotides. 

```{r}
# what line 128 is checking for
legal_dna = c('A', 'T', 'C', 'G')
> any(testMutIn$alt %in% legal_dna)
[1] FALSE
```

A possible correction to incorporate insertion data would be a grepl() with a regex expression.
```{r}
if (!(any(mutations$ref %in% legal_dna) && grepl("^[ATCG]+$", mutations$alt))) stop("Reference and alternate alleles must be A, T, C or G")
```

When activeDriver is run with this quick fix, the following error message is returned. 
```{r}
 Error in .get_3n_context_of_mutations(mutations, reference) : 
   Dataset must contain SNVs 
```

This error message comes from line 31 in <code>format_muts.R</code>. 

The current activeDriver does not run with insertion only mutation data.

**Comment by CathyCha** [comment]
<h4>Correction </h4>

The possible suggestion for line 128 with grepl() should be:

```{r}
if ((any(testMutDel$ref %in% legal_dna) && all(grepl("^[ATCG]+$", testMutDel$alt)))) stop("Reference and alternate alleles must be A, T, C or G")
```

**Comment by reimand0** [comment]
this issue is addressed in ActiveDriverWGS v.1.1.0. Thanks for reporting.
