### ISSUE TITLE
GRCh38 reference files

### ISSUE THREAD

**Issue by bkinnersley** [reimandlab/ActiveDriverWGSR#3]
Hello,

Thank you for this very useful software package! I was just wondering if there are plans to add support for GRCh38, or if it would be possible to provide details for how other users could create GRCh38 reference files suitable for use with ActiveDriverWGSR?

Thanks very much

Best wishes

Ben

**Comment by reimand0** [comment]
We have an unstable and unverified version of ActiveDriverWGS supporting multiple reference genomes, in a separate branch here: https://github.com/reimandlab/ActiveDriverWGSR/tree/genomeVariety. Work is ongoing to create an updated package in CRAN. Stay tuned!

**Comment by bkinnersley** [comment]
Thanks very much! It seems that currently the recovery directory option in this branch (https://github.com/reimandlab/ActiveDriverWGSR/blob/genomeVariety/R/ActiveDriverWGS.R) is not working as previously (https://github.com/reimandlab/ActiveDriverWGSR/blob/master/R/ActiveDriverWGS.R), I don't know if it is related to this commit https://github.com/reimandlab/ActiveDriverWGSR/commit/bdc341d3888ba002301a5a8ac720eaf0b8b9fbc1

**Comment by reimand0** [comment]
Thanks for letting us know. will investigate. This fix is certainly quite
cryptic.

**Comment by reimand0** [comment]
Hi Ben, 
the new version 1.1.0 now supports human reference genome hg38 and mouse genomes mm9 and mm10. You can get it from GitHub (master) while CRAN review is in progress. Please let me know of any comments or findings. 
best,
Jüri
