### ISSUE TITLE
Adjacent elements falling within background flanks

### ISSUE THREAD

**Issue by will-NYGC** [reimandlab/ActiveDriverWGSR#4]
How does ADWGS_test handle the case when an adjacent element sits in the background window? It seems like these are not excluded and if the adjacent element is itself hypermutated, it could inflate the background mutation rate.  Does this happen in practice?

**Comment by reimand0** [comment]
All elements are tested independently so if an adjacent element falls into the background sequence then this is considered as part of the background mutation rate. Generally this is not a concern, assuming that the elements are much smaller than the entire background region (100s of bps for elements vs 100k for background). 

If the background contains a large number of frequently mutated regions then it becomes an indicator that the entire background region is potentially hypermutated and the tested element less likely to be a positively selected candidate driver. 

One potential issue with this strategy occurs when testing adjacent elements of known driver genes with many protein-coding mutations (such as promoter of TP53, for example). These protein-coding mutations would then inflate the background mutation rate and make the promoter mutations appear less significant. Some potential ways to get around this is to exclude exons from the backgrounds, or exclude (some) protein-coding mutations from the dataset. 

hope this helps!
best,
Jüri
