### ISSUE TITLE
numbers of columns of arguments do not match

### ISSUE THREAD

**Issue by alhafidzhamdan** [reimandlab/ActiveDriverWGSR#8]
Hi there,

I ran ActiveDriverWGS using this command:
```
drivers <- ActiveDriverWGS(mutations = unique_mutations,
                elements = elements,  
                ref_genome = "hg38",
                window_size = 50000,
                filter_hyper_MB = 30,
                mc.cores = 16,
                recovery.dir = recovery_dir)
```

```
> head(unique_mutations)
    chr      pos1      pos2 ref alt patient
1: chr1  16965728  16965728   G   G  BCCA1T
2: chr1  20345468  20345468   G   G  BCCA1T
3: chr1  21823627  21823627   C   C  BCCA1T
4: chr1 109192794 109192794   A   A  BCCA1T
5: chr1 111766331 111766331   T   T  BCCA1T
6: chr1 112913924 112913924   A   A  BCCA1T
```

```
> head(elements)
    chr start   end                       id
1: chr1 11869 14409        ENSG00000223972.5
2: chr1 11869 14409        ENST00000456328.2
3: chr1 11869 12227 exon:ENST00000456328.2:1
4: chr1 12613 12721 exon:ENST00000456328.2:2
5: chr1 13221 14409 exon:ENST00000456328.2:3
6: chr1 12010 13670        ENST00000450305.2

```

However i keep getting this error:

```
7 remove hypermut, n= 865012 ,  29 %
hypermuted samples:  BCCA15T BCCA22T BCCA38T BCCA43T BCCA9T DKFZ-KZWST1 NYGC7T 

reversing 0 positions
Removing  0  invalid SNVs & indels

Number of Elements with 0 Mutations:  1759191 
Tests to do:  447249 
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
In addition: Warning message:
In parallel::mclapply(1:length(not_done), function(i) { :
  all scheduled cores encountered errors in user code
```

Not sure what's causing the error, would you be able to help troubleshoot? Many thanks!

Al

**Comment by reimand0** [comment]
Hi Al,

Not easy to say based on your code, but try removing the recovery dir
option and see if it works. Also does the mclapply error occur immediately
or after it has been processing for a while?

best,
Jüri

**Comment by reimand0** [comment]
one more potential explanation - if memory runs out on one core (for the mclapply part), that sub-process will crash and return no results, potentially cascading to rbind that fails to tie together results from the different processes. For us this happens on the compute cluster where processes have fixed memory limits. Any sub-process may land on a longer genomic region that needs more memory to process, for example.

**Comment by alhafidzhamdan** [comment]
Hi Juri, thanks for getting back so quickly.
I've removed the recovery dir before and it's the same error.
It occurs after a while, and there seem to be recovery files in the recovery dir.
I am using my laptop here, with 16Gb ram. How would you recommend fixing this?
Thanks.
Al

**Comment by reimand0** [comment]
Hi Al,

Couple of things to try:
- run fewer cores. That may help the process complete because it is more
likely that none of the sub-processes will run out of memory.
- run a first subset of your elements. If you manage to execute a full run
and return results then that indicates that there is a problematic element
further down in your list that fails to run. Most likely it encounters a
memory error. - In particular if you have a very large genomic element like
the DMD gene then that may force your process to crash.
- ultimately, running on one core will crash at the specific element that
causes the crash and you can figure it out based on your list and the files
in the recovery dir.

sorry this may be a little vague but hopefully helpful.

Jüri

**Comment by alhafidzhamdan** [comment]
Hi Juri,

I've tried fewer cores ie 4:
```
> results <- ActiveDriverWGS(mutations = ADWGS_mutations, 
+                            elements =elements_to_test, 
+                            ref_genome = "hg38",
+                            window_size = 50000,
+                            filter_hyper_MB = 10,
+                            mc.cores = 4,
+                            recovery.dir = "Data/Non-coding/")
17 remove hypermut, n= 1427636 ,  48 %
hypermuted samples:  BCCA14T BCCA15T BCCA17T BCCA22T BCCA25T BCCA38T BCCA39T BCCA40T BCCA41T BCCA43T BCCA8T BCCA9T C3L-00677T DKFZ-KZWST1 DKFZ-NAFCT1 NYGC20T NYGC7T 

reversing 0 positions
Removing  0  invalid SNVs & indels

Number of Elements with 0 Mutations:  34510 
Tests to do:  6265 
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
In addition: Warning message:
In parallel::mclapply(1:length(not_done), function(i) { :
  all scheduled cores encountered errors in user code

```

It crashed after 1 minute.
How do I go about dealing with the rsav file? and what would you recommend with the troubesome element if any?
A

**Comment by reimand0** [comment]
At this point I would recommend running a minimal example and use just one core with mc.cores=1. Can you just test one gene in the element set, for example? I would suspect that some of your input files have a formatting error that may occur deeper in the files. 

rsav files can be opened in R using print(load("filename.rsav")) and the print() will give you the name of the object that was loaded. 

hope this helps!

**Comment by alhafidzhamdan** [comment]
Hi there,

I've now tried mc.cores  =1 with :

```
> results <- ActiveDriverWGS(mutations = ADWGS_mutations, 
+                            elements = promoters[promoters$id %in% c("TERT"),], 
+                            ref_genome = "hg38",
+                            window_size = 50000,
+                            filter_hyper_MB = 10,
+                            mc.cores = 1)

17 remove hypermut, n= 1427636 ,  48 %
hypermuted samples:  BCCA14T BCCA15T BCCA17T BCCA22T BCCA25T BCCA38T BCCA39T BCCA40T BCCA41T BCCA43T BCCA8T BCCA9T C3L-00677T DKFZ-KZWST1 DKFZ-NAFCT1 NYGC20T NYGC7T 

reversing 0 positions
Removing  0  invalid SNVs & indels

Number of Elements with 0 Mutations:  0 
Tests to do:  1 
.
> results
    id  pp_element element_muts_obs element_muts_exp element_enriched pp_site site_muts_obs site_muts_exp site_enriched fdr_element
1 TERT 0.002641642                1                0             TRUE       1            NA            NA            NA 0.002641642
  fdr_site has_site_mutations
1        1 
````

Testing a single gene with the option "recovery.dir" always gave this error:
```
..Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```
So how do I go about checking my elements file?
I can't seem to find anything wrong with it. 

```
> str(promoters)
'data.frame':	19001 obs. of  4 variables:
 $ chr  : chr  "chr1" "chr1" "chr1" "chr1" ...
 $ start: num  68091 451578 451578 451578 924731 ...
 $ end  : num  69191 452678 452678 452678 925831 ...
 $ id   : chr  "OR4F5" "OR4F3" "OR4F29" "OR4F16" ...

```

Appreciate your time looking into this! 
A

**Comment by reimand0** [comment]
Hello - apologies for the long silence. Would you be willing to share your
data with me and the exact code? I will do my best to reproduce this error
and fix the package.
best,
Jüri
