### ISSUE TITLE
indel ref and alt alleles query

### ISSUE THREAD

**Issue by bkinnersley** [reimandlab/ActiveDriverWGSR#9]
Hello,

I just wanted to clarify whether it was essential for the ref/alt alleles for indel mutations to be represented solely by A/C/T/G bases or whether mutation representations containing "-" were acceptable (as long as pos1/pos2 are consistent with these)?

 In the documentation (https://htmlpreview.github.io/?https://github.com/reimandlab/ActiveDriverWGSR/blob/master/doc/ActiveDriverWGSR.html#mutations) it is suggested that allele representations should only include A/T/C/G, but the example cll_mutations data contains mutations where the ref/alt allele is represented by "-":

![image](https://user-images.githubusercontent.com/34348939/122776141-b8afdc80-d2a2-11eb-8f54-a2a5d23351a1.png)

Thanks very much

Best wishes

Ben

**Comment by reimand0** [comment]
Hi Ben,

yes, you can specify indels like this! Let me know if you have any other
questions.

best,
Jüri

**Comment by bkinnersley** [comment]
Hi Jüri,

Thank you for the quick reply! That's very helpful thanks,

I just wanted to check how the pos1 and pos2 positions are estimated for insertions? Taking an example in the cll_mutations object:
chr: chr10
pos1: 10498176
pos2: 10498180
ref: -
alt: GAAAAA
My understanding would be that the "MAF" format representation of this mutation start and end position would be with respect to the reference genome, so for any size insertion the start_pos would be 10498176 and the end_pos would be start_pos + 1 (10498177) - should that be the approach when creating input for indels for ActiveDriverWGSR?

Thanks very much

Best wishes

Ben

**Comment by reimand0** [comment]
Yes, we have based this on the MAF format. The main thing the indel positioning will affect is whether it overlaps the coordinates of a functional genomic element (such as a TFBS). It may be worth checking for edge cases such as those directly on the boundary of an element.
